name: Firebaseに Build & Deploy & Slack通知
'on':
  push:
    branches:
      - master
      # - dev

jobs:
  build_and_deploy_prod:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v2

      - name: Nuxtアプリのビルド(環境変数設定含む)
        run: npm ci && npm run build

      - name: NuxtアプリをHostingへデプロイ
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project=${{ secrets.FIREBASE_PROJECT_ID }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
